### ISSUE TITLE
Tabular view

### ISSUE THREAD

**Issue by stevencox** [frostyfan109/tranql#105]
I'm filtering the view by robokop but one rtx row still shows. Am I reading this correctly?

![image](https://user-images.githubusercontent.com/306971/62584754-e6910100-b883-11e9-8361-016c58d9cd18.png)

... ok, I'm guessing this means that the node was returned by both reasoners. Is that the idea?

**Comment by frostyfan109** [comment]
Yep. Right now its an inclusive match. If the string ("-robokop -rtx") _includes_ the substring ("-robokop") it will match the row. I found that this was necessary because of the line breaks resulting in things not matching properly.

Let me know if you think there should be a setting to switch this to an exact match. You can technically do it right now with the regex syntax (/^- robokop$/), but this is not going to be the case for most users.
