### ISSUE TITLE
Tabular View - Node Columns

### ISSUE THREAD

**Issue by stevencox** [frostyfan109/tranql#109]
There are a lot of columns for nodes in the tabular view. Only a fraction are shown in the screenshot. Many of the column headers are not readable. Do we need to select a manageable subset for now?

![image](https://user-images.githubusercontent.com/306971/62585594-80a67880-b887-11e9-9159-44c40912802f.png)

**Comment by frostyfan109** [comment]
Yeah, it gets a bit crazy with large graphs.

We could offer a small popup interface that functions sort of similarly to the legend so that you can toggle an attribute to easily hide it. This would also allow us to start the table off with only a subset of properties we've predetermined as important, and the user could selectively enable other columns that they want to see.

**Comment by frostyfan109** [comment]
Added in commit 8b603657bf31767faaddbb5722bcf2e62116de8b
