### ISSUE TITLE
Are workflow-4/5 queries (with icees) dropping content?

### ISSUE THREAD

**Issue by stevencox** [frostyfan109/tranql#16]
Formerly, when I ran the workflow-5 or workflow-4 queries (tranql/queries/*), the legend included population_of_individual_organism, chemical_substance, etc. Now, it seems to contain far fewer items and the result graph is much smaller. Haven't had a chance to investigate but are the TimeOut errors from the async module dropping answers? Maybe try w/o async.

**Comment by frostyfan109** [comment]
It seems like ICEES is currently not working with TranQL because TranQL is failing to fetch its schema. I'll try to look into if it's a problem with TranQL or with ICEES.

**Comment by frostyfan109** [comment]
There doesn't seem to be any issues with requests timing out when I run it, but I am missing population_of_individual_organisms. I'll look further into it and see if I can figure out what's going on.

**Comment by frostyfan109** [comment]
Some of these results could have been in part due to a bug I found occurring in queries yielding very large knowledge graphs. configureMessage was being called after translateGraph, resulting in it capping the node connectivity range at 1000 (the default/previous). If some nodes in the query had a connectivity higher than this (e.g. Workflow 5 v3), it would not render correctly the first time you ran it (after running it two times consecutively configureMessage would set the range to be correct [the previous query's range]).

I still cannot get population_of_individual_organisms to render, but this is because it is being filtered out by the render chain. The knowledge graph still contains the node. Perhaps this could be a bug as well?
