### ISSUE TITLE
Autocomplete

### ISSUE THREAD

**Issue by stevencox** [frostyfan109/tranql#47]
Autocomplete is not working. Investigate making it work with CodeMirror2 or, if not, reverting to CodeMirror.

/beta2

**Comment by frostyfan109** [comment]
Fixed.

**Comment by stevencox** [comment]
This is coming along **really** nicely.

One thing to think about, when I start with this and choose a predicate via autocomplete:

![image](https://user-images.githubusercontent.com/306971/62813598-b8a4fa00-bad9-11e9-8476-3db02c88732a.png)

The complete-to-arrow logic seems to overwrite characters in the query rather than inserting so the next state is:

![image](https://user-images.githubusercontent.com/306971/62813640-dd00d680-bad9-11e9-8648-2d2f675f763f.png)

Anyway, this feature will be a big help.

**Comment by frostyfan109** [comment]
Huh, that's strange. It's supposed to replace the selection of characters already entered into the predicate. For example, if I had `select gene-[direct` it would replace `direct` with something like `directly_interacts_with`. This is so that you don't end up with `select gene-[directdirectly_interacts_with]->` I guess rather than replacing it must be overwriting from the starting index.

Update: It looks like codemirror's autocomplete doesn't work quite how I thought it had and already natively inserts text rather than overwriting it. Since I had it trying to insert instead of overwrite even though it already inserts, it ended up overwriting instead.

**Comment by frostyfan109** [comment]
Fixed
